apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dev-poc-config-svc
spec:
  serviceName: dev-poc-config-svc
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: poc_panasonic
        app: dev-poc-config-svc
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: dev-poc-config-svc
          image: "consul:0.9.3"
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=1"
            - "-client=0.0.0.0"
            - "-datacenter=dc1"
            - "-data-dir=/consul/data"
            - "-domain=cluster.local"
            - "-server"
            - "-raft-protocol=1"
            - "-ui"
            - "-retry-join=dev-poc-config-svc"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  PATH=/bin:$PATH
                  ps -ef | grep "[c]onsul agent"
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  PATH=/bin:$PATH
                  consul operator raft list-peers | grep leader && [ $(/bin/consul operator raft list-peers | wc -l) -gt 4 ]
            initialDelaySeconds: 600
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /consul/data
            - name: config
              mountPath: /consul/config
            - name: tls
              mountPath: /etc/tls
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
      volumes:
        - name: config
        - name: tls
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi